### ISSUE TITLE
Crashes when opening bookmarks after data sync

### ISSUE THREAD

**Issue by freeman2501** [zerok/fosdem-to-go#1]
Initially, when browsing through the 2024 program and bookmarking items, everything works perfectly: bookmarking works, you can browse through them on the bookmarks tab of the app. 
However, after doing a program sync (cloud icon right top), I can no longer open the bookmarks tab. When I want to open the bookmarks tab the app crashes/quits. I have encountered this 2 times. The only fix I found was uninstalling the app and it's data, reinstalling the app and readding all bookmarks which is offcourse ... cumbersome :)
I did not have this issue in the 2023 edition so I think some functionality in the bookmarks section does not play nice with the 2024 dataset/dataset changes somehow.

Hopefully you can get a fix released before 3/4 Feb ...

iPhone 13
IOS version 17.2.1

**Comment by zerok** [comment]
Hi 🙂 I just also tried the following:

- Have already the 2023 data, hit the sync button, clicked bookmarks -> crash
- 2024 data (not previously downloaded), add talk to bookmarks, click bookmarks -> no crash
- 2024 data present +bookmarks present, clicking sync, clicking bookmarks -> no crash

I will try to find some time for it some time this week :)

**Comment by zerok** [comment]
0.3.6 is currently in Apple's review pipeline. It contains a change that adds another check to the bookmarks listing, filtering out talks that are no longer included in the official schedule. Please let me know if this fixes your issue once you get a chance to install that new version 🙂

**Comment by freeman2501** [comment]
I updated to version 0.3.6 today and did some intensive testing (adding bookmarks and removing bookmarks in 2024, switching to 2023 and doing the same, switching back to 2024, updating the program several times, ...). I had no more crashes so I think the issue is fixed. Thank you for the update and for the great (and extremely convenient) Fosdem app. Hopefully see you in a few weeks in Brussels? :)

**Comment by zerok** [comment]
Thank you for testing the fix ❤️ 

Yes, I will be there and perhaps eventually revive this project (if I find the time ^_^)!
